# Generated by Django 5.0.3 on 2024-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_by_admin',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Creado por Admin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='users/', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
